server:
  port: 8088
  servlet:
    session:
      timeout: 3600
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
#    url: jdbc:mysql://rm-2zewnss316uzyzo66wo.mysql.rds.aliyuncs.com:3306/bcp_server_c?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: pub_account
#    password: Pub_account
    url: jdbc:mysql://localhost:3306/bcp_server_c?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Qq123903
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.bcp.serverc.mapper
  # 不配置这个mapper中自定义的sql无法绑定
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    # 进行自动映射时，数据以下划线命名，如数据库返回的"order_address"命名字段是否映射为class的"orderAddress"字段。默认为false
    map-underscore-to-camel-case: true

# 打印sql执行
logging:
  level:
    com.bcp.serverc.mapper : debug
